spring:
    application:
        name: itsol-registry

server:
    port: 8761
    ssl:
        key-store: keystore.p12
        key-store-password: ItsolRegistry
        keyStoreType: PKCS12
        keyAlias: ItsolRegistry

logging:
    file: target/itsol-registry.log

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "logfile"]
    endpoint:
        health:
            show-details: when_authorized
        shutdown:
            enabled: true
    health:
        mail:
            enabled: false

eureka:
    instance:
        hostname: localhost-com
        appname: itsol-registry
        instanceId: itsolRegistry:${spring.application.instance-id:${random.value}}
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.endpoints.web.base-path}/info
        health-check-url-path: ${management.endpoints.web.base-path}/health
        metadata-map:
            zone: primary
            profile: ${spring.profiles.active}
            version: ${info.project.version}
    client:
        enabled: true
        fetch-registry: false
        register-with-eureka: false
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
        service-url:
            defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        enable-self-preservation: true
    dashboard:
        path: /registry
    datacenter: Itsol-DataCenter
    environment: Itsol-Environment
